version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - mynetwork

  app:
    build:
      context: node
    container_name: app
    entrypoint: > 
      dockerize -wait tcp://db:3306 -timeout 10s 
      docker-entrypoint.sh 
      node index.js
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_node
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=123456
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge