version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - mynetwork

  app:
    build:
      context: node
    container_name: app
    entrypoint: > 
      dockerize -wait tcp://db:3306 -timeout 10s 
      docker-entrypoint.sh 
      node index.js
    networks:
      - mynetwork
    tty: true
    depends_on:
      - db

  db:
    build:
      context: db
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge