version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - mynetwork

  app:
    build:
      context: node
    container_name: app
    entrypoint: > 
      dockerize -wait tcp://db:3306 -timeout 2s 
      docker-entrypoint.sh 
      node index.js
    networks:
      - mynetwork
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge